
includedir = ./include
srcdir = ./src
objdir = ./obj

dir_fileutils = ${srcdir}/fileUtils
CXXFLAGS = -Wall -O3 -m64 -std=c++11 -pedantic

FileStreamer.o:
	g++ ${CXXFLAGS} -I ${includedir} -c ${dir_fileutils}/FileStreamer.cpp -o ${objdir}/FileStreamer.o